steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/arctic-rite-497707-s6/clientchat-v2:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/arctic-rite-497707-s6/clientchat-v2:latest'
      - 'backend'
images:
  - 'gcr.io/arctic-rite-497707-s6/clientchat-v2:latest'
  - 'gcr.io/arctic-rite-497707-s6/clientchat-v2:$COMMIT_SHA'
